export const next = 'loop'
export const exercises = {
  'primitives': {},
  'escape-str': {},
  'arr': {},
  'obj': {},
  'nested': {},
  'id': {},
  'get-length': {},
  'last-first-kiss': {},
  'more-or-less': {},
  'concat-str': {},
  'get': {},
  'set': {},
  'circular': {},
  'biggie-smalls': {},
  'sign': {},
  'is': {},
  '何': {},
}
